# Generated by Django 3.1.7 on 2021-04-06 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'), ('music', 'Music'), ('lifestyle', 'Lifestyle')], default=1, max_length=9)),
                ('body', djrichtextfield.models.RichTextField()),
                ('views_count', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
