# Generated by Django 3.1.7 on 2021-04-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210406_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'), ('music', 'Music'), ('lifestyle', 'Lifestyle')], max_length=9, null=True),
        ),
    ]
