# Generated by Django 3.1.7 on 2021-04-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210407_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('health', 'Health'), ('tech', 'Technology'), ('food', 'Food'), ('travel', 'Travel'), ('music', 'Music'), ('lifestyle', 'Lifestyle')], max_length=9, null=True),
        ),
    ]
